language: node_js
node_js: "node"

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install --frozen-lockfile

script:
  - $(npm bin)/cypress run --record

after_success:
  - ./deploy.sh
